# $Id$
#
# Makefile to build OGR Mongo driver
#
GDAL_ROOT	=	..\..\..

OBJ = ogrmongodriver.obj ogrmongodatasource.obj ogrmongolayer.obj ogrmongoreader.obj

#EXTRAFLAGS = -I. -I.. -I..\..
EXTRAFLAGS =	-I.. -I..\..  -I..\geojson -I$(MONGO_INC_DIR)

!INCLUDE $(GDAL_ROOT)\nmake.opt


default:	$(OBJ)

clean:
	-del *.obj *.pdb